# Generated by Django 6.0.1 on 2026-02-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_game_portfolio_holding_gameparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='average_price',
        ),
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='api.game'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='investment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'game')},
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['portfolio'], name='api_holding_portfol_e50844_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'executed_at'], name='api_transac_portfol_772667_idx'),
        ),
    ]
