# Generated by Django 6.0.1 on 2026-02-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_holding_average_price_game_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='api_stockpr_symbol_5ac4a3_idx')],
            },
        ),
    ]
