# Generated by Django 6.0.1 on 2026-02-08 21:37

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.db.models.functions.datetime.Now),
        ),
    ]
