# Generated by Django 6.0.1 on 2026-02-08 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stockprice_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='api_stockpr_symbol_5ac4a3_idx',
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['symbol', 'date'], name='api_stockpr_symbol_a3e398_idx'),
        ),
    ]
