# Generated by Django 6.0.1 on 2026-02-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stockprice_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('symbol', 'date')},
        ),
    ]
