# Generated by Django 6.0.1 on 2026-02-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stockprice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
